improve detection of invalid ip/hostname

diff --git a/roku_scripts/install b/roku_scripts/install
--- a/roku_scripts/install
+++ b/roku_scripts/install
@@ -70,15 +70,11 @@ if [ ! -e 'manifest' ]; then
     exit 1
 fi
 
-if [ -z "${ROKU_IP}" ]; then
-    echo 'missing destination device: include a device ip or hostname' >&2
-    exit 1
-    # comment out above two lines & replace this with a fallback/default device ip if desired:
-    ROKU_IP="" 
-fi
-
 # the destination device can be a hostname from the hosts file
-[[ "${ROKU_IP}" =~ [^.0-9] ]] && ROKU_IP=$(cat /etc/hosts | awk "/${ROKU_IP}/ { print \$1 }")
+[[ -z "${ROKU_IP}" || "${ROKU_IP}" =~ ^([0-9a-fA-F]{4}:){7}[0-9a-fA-F]{4}$ || \
+    "${ROKU_IP}" =~ ^([0-9]{1,3}\.){3}[0-9]{1,3}$ ]] || \
+    ROKU_IP=$(cat /etc/hosts | awk "/${ROKU_IP//\//\\/}/ { print \$1 }")
+[ -z "${ROKU_IP}" ] && echo 'rokupkg: error: invalid hostname/ip' >&2 && exit 1
 
 # increment manifest build no.
 if [ "${INCREMENTBUILDNO}" == "true" ]; then
